export const HANDLE_MUSIC_QUERY = 'HANDLE_MUSIC_QUERY';
export const ADD_MUSIC_TO_CURRENT_PLAYLIST = 'ADD_MUSIC_TO_CURRENT_PLAYLIST';
export const SET_CURRENT_PLAYLIST = 'SET_CURRENT_PLAYLIST';
export const SET_CURRENT_MUSIC = 'SET_CURRENT_MUSIC';
