export const HANDLE_MUSIC_QUERY = 'HANDLE_MUSIC_QUERY';

export const ADD_MUSIC_TO_CURRENT_PLAYLIST = 'ADD_MUSIC_TO_CURRENT_PLAYLIST';

export const NEXT_MUSIC_FROM_CURRENT_PLAYLIST = 'NEXT_MUSIC_FROM_CURRENT_PLAYLIST';
export const PREV_MUSIC_FROM_CURRENT_PLAYLIST = 'PREV_MUSIC_FROM_CURRENT_PLAYLIST';

export const SET_CURRENT_PLAYLIST = 'SET_CURRENT_PLAYLIST';
export const SET_CURRENT_MUSIC = 'SET_CURRENT_MUSIC';

export const APP_STATE_CONTROLLER_START = 'APP_STATE_CONTROLLER_START';
export const APP_STATE_CONTROLLER_SUCCESS = 'APP_STATE_CONTROLLER_SUCCESS';
export const APP_STATE_CONTROLLER_FAIL = 'APP_STATE_CONTROLLER_FAIL';

export const APP_HANDLE_ERROR_MESSAGE = 'APP_HANDLE_ERROR_MESSAGE';
