export const HANDLE_USER = 'HANDLE_USER';

export const ADD_PLAYLIST = 'ADD_PLAYLIST';
export const DEL_PLAYLIST = 'DEL_PLAYLIST';

export const DEL_MUSIC_FROM_PLAYLIST = 'DEL_MUSIC_FROM_PLAYLIST';

export const USER_STATE_CONTROLLER_START = 'USER_STATE_CONTROLLER_START';
export const USER_STATE_CONTROLLER_SUCCESS = 'USER_STATE_CONTROLLER_SUCCESS';
export const USER_STATE_CONTROLLER_FAIL = 'USER_STATE_CONTROLLER_FAIL';

export const USER_HANDLE_ERROR_MESSAGE = 'USER_HANDLE_ERROR_MESSAGE';
